version: '3.9'
services:
  nginx_webserver:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./main/verteilte-anwendungen/test.html:/usr/share/nginx/html/index.html

# We make four distinct layers so if there are application changes the library layers can be re-used


# We make four distinct layers so if there are application changes the library layers can be re-used
